language: rust
rust:
    - nightly
before_install:
    - sudo apt-get update
install:
    - sudo apt-get install -y python2 python-crypto
    - sudo pip install passlib
    - sudo pip install jsonschema
script:
    - cargo build --verbose
    - python test_harness.py
