language: rust
rust:
    - nightly
before_install:
    - sudo apt-get update
install:
    - sudo apt-get install -y python3 python3-crypto python3-setuptools
    - sudo easy_install3 jsonschema
script:
    - cargo build --verbose
    - python3 test_harness.py
