language: rust
rust:
    - nightly
before_install:
    - sudo add-apt-repository ppa:fkrull/deadsnakes -y
    - sudo apt-get update -q
install:
    - sudo apt-get install -y python3.4
    - sudo pip3 install passlib
    - sudo pip3 install jsonschema
    - sudo pip3 install pycrypto
script:
    - cargo build --verbose
    - python3 test_harness.py
