[package]

name = "theca"
version = "0.6.0"
authors = ["Roland Shoemaker <roland@bind.es>"]

[lib]
name = "theca"
path = "src/theca/lib.rs"

[[bin]]
name = "theca"
test = false
doc = false

[dependencies]
time = "*"
rustc-serialize = "*"
docopt = "*"
rust-crypto = "*"
regex_macros = "*"
